In [20]:
import numpy as np

In [ ]:
# Create Array, Matrix
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [22]:
b = np.array([[1,2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

In [24]:
# Shape
print(a.shape, b.shape)

(4,) (2, 2)


In [26]:
# Reshape
c = a.reshape((4, 1))
c.shape

(4, 1)

In [30]:
d = a.reshape((2, 2, -1))
d.shape

(2, 2, 1)

In [33]:
# Concatenate
a = np.array([1, 2, 3])
b = np.array([4, 5])

c = np.concatenate((a, b))
c

array([1, 2, 3, 4, 5])

In [35]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a * b
c

array([ 4, 10, 18])

In [36]:
c = np.array([10])
d = a + c
d

array([11, 12, 13])

In [38]:
e = a + b
e

array([5, 7, 9])

In [39]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape

(8,)

In [43]:
b = a[2:7:2]
b

array([3, 5, 7])

In [45]:
c = a[a>3]
c

array([4, 5, 6, 7, 8])

In [46]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
sum_a = np.sum(a)
sum_a

np.int64(36)

In [50]:
max_a = np.max(a)
max_a

np.int64(8)

In [51]:
min_a = np.min(a)
min_a

np.int64(1)

In [52]:
a = np.array([6, 7, 9, 10, 5, 4, 3, 6])
b = np.sort(a)
b

array([ 3,  4,  5,  6,  6,  7,  9, 10])

In [55]:
a = np.random.randint(-100, 100, (3, 4))
a

array([[ 63,  84, -54,  -2],
       [-18,  65, -84, -64],
       [ 72,  54,  72, -84]], dtype=int32)

In [68]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [70]:
# Normalize
mean_a = np.mean(a)
mean_a

np.float64(2.0)

In [71]:
std_a = np.std(a)
std_a

np.float64(0.816496580927726)

In [77]:
norm_a = (a-mean_a)/std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [78]:
np.mean(norm_a)

np.float64(0.0)

In [79]:
np.std(norm_a)

np.float64(0.9999999999999999)